name: test

on:
  workflow_dispatch:

env:
  TEST_REPOSITORY: tmtenbrink/rustfrc

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
          include:
            - py-version: 3.9
              py-pep-425: 'cp39-cp39'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Checkout rustfrc
      uses: actions/checkout@v2
      with:
        repository: ${{ env.TEST_REPOSITORY }}
        path: ${{ env.TEST_REPOSITORY }}
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py-version }}
    - name: Build manylinux Python wheels
      uses: './'
      with:
        py-version: "python${{ matrix.py-version }}"
        py-pep-425: ${{ matrix.py-pep-425 }}
        package-path: ${{ env.TEST_REPOSITORY }}
    - uses: actions/upload-artifact@v2
      with:
        name: wheels-manylinux
        path: ${{ env.TEST_REPOSITORY }}/dist